features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
website_width: ''
top_region: 1
main_region: 0
bottom_region: 1
footer_region: 1
equal_width: 0
current_theme: w3-theme-green
color_page_wrapper: ''
color_header: ''
color_primary_menu: ''
color_welcome_text: ''
color_highlighted: ''
color_top_container: ''
color_top_first: ''
color_top_second: ''
color_top_third: ''
color_page_title: ''
color_main: ''
color_breadcrumb: ''
color_sidebar_first: ''
color_content: 'w3-link-blue-grey w3-link-blue-gray-hover'
color_sidebar_second: 'w3-link-blue-grey w3-link-dark-gray-hover'
color_bottom_container: ''
color_bottom_first: ''
color_bottom_second: ''
color_bottom_third: ''
color_bottom_forth: ''
color_footer_container: ''
color_footer_first: ''
color_footer_second: ''
color_footer_third: ''
color_footer_menu: ''
color_copyright: ''
show_social_icon: 0
facebook_url: ''
twitter_url: ''
pinterest_url: ''
google_plus_url: ''
linkedin_url: ''
instagram_url: ''
youtube_url: ''
drupal_url: ''
rss_url: ''
copyright_text: 'Copyright 2020-2021 - CC BY-NC-SA'
show_credit_link: 0
